### ISSUE TITLE
VAC308.kmk fails because kmk_redirect does not support pipes.

### ISSUE THREAD

**Issue by StevenLevine** [bitwiseworks/kbuild-os2#1]
When configured to build with VAC308.kmk, the build fails with:

warning EDC1004: Option "/@unixroot/usr/bin/kDepPre.exe" is not
recognized. warning EDC1004: Option "/f" is not recognized.
warning EDC1004: Option "/s" is not recognized.
error EDC1023: Unable to find source file
D:/sla_dev2/testkbuild/out/os2.x86/release/obj/testme/testme.obj.dep.
warning EDC1004: Option "/t" is not recognized.
warning EDC1004: Option "/" is not recognized.

The attached testcase:

[testme_c-20181022.zip](https://github.com/bitwiseworks/kbuild-os2/files/2512966/testme_c-20181022.zip)

illustrates this.  The failure occurs because kmk_redirect will not spawn a shell required by TOOL_VAC308_COMPILE_C_CMDS.

The fix is the restore some of the code from knut's VAC308.kmk.  The included Config.kmk-works shows which code needs to be restored.

**Comment by SilvanScherrer** [comment]
yes we need to resync kbuild. as a lot fixes/changes happened since we forked.

**Comment by dmik** [comment]
@StevenLevine you are referring to this upstream fix I believe: http://trac.netlabs.org/kbuild/changeset/3055. Silvan is right: It's missing from our RPM build simply because last time we synced was r3052 (check here https://github.com/bitwiseworks/kbuild-os2/commits/master) — just a few commits before.

And I now recalled that Yuri complained about that as well. I believe it was him who convinced Knut to fix that but somehow our fork (and RPM) was not updated.

A new refresh should fix it then. I will do that in a few days.

**Comment by dmik** [comment]
Merging new kBuild in, turns out to be not that easy, a lot of changes and build breaks.

**Comment by dmik** [comment]
I've merged kBuild r3236 and cooked a test RPM. The attached example builds fine with it. I will run the new kmk for a few days and will put it to exp if it's fine.

**Comment by dmik** [comment]
The new kBuild RPM 0.1.9998-10 is in exp. Feel free to test and reopen this ticket if this problem persists.
