### ISSUE TITLE
kbuild QuickReference-kmk.html corrupted in https://github.com/bitwiseworks/kbuild-os2

### ISSUE THREAD

**Issue by StevenLevine** [bitwiseworks/kbuild-os2#2]
QuickReference-kmk.html is corrupted in kbuild-0.1.9998-9.oc00.i686.rpm.  The same appears to be true for the original in https://github.com/bitwiseworks/kbuild-os2.

In knut's svn we have:

QuickReference-kmk.html:13
:Date: $Date: 2009-04-18 04:05:47 -0800 (Sat, 18 Apr 2009) $

In the bww git repo, we have:

QuickReference-kmk.html:13
:Date: $Date: 2009-04-18 16:05:47 +0400 (ðíð▒, 18 ð░ð┐ÐÇ 2009) $

**Comment by dmik** [comment]
It's not corrupted — its SVN keyword substitution in action (the dark CVS legacy). As [docs](http://svnbook.red-bean.com/en/1.7/svn.advanced.props.special.keywords.html) show, `$Date` is replaced with the date in the local time zone and with a localized date string in parenthesis. A person who came up with this idea apparently didn't think very well because this obviously breaks the source if it deals with 8-bit encodings (and also makes the timestamp string inconsistent between different time zones).

What happened here is that I checked out this file from SVN locally with LANG=ru_RU (which defaults to cp866 on OS/2). This brought Cyrillics in parenthesis. These Cyrillics were then converted to UTF-8 (the default github encoding) and look pretty well here when viewed through GitHub, https://github.com/bitwiseworks/kbuild-os2/blob/master/kBuild/doc/QuickReference-kmk.html:
```
:Author: David Goodger
:Contact: goodger@users.sourceforge.net
:Date: $Date: 2009-04-18 16:05:47 +0400 (Сб, 18 апр 2009) $
:Revision: $Revision: 2340 $
:Copyright: This stylesheet has been placed in the public domain.
```
This file actually looks fine on my machine even when it comes from RPM because I have LANG=ru_RU However, in your case the 8-bit encoding is cp437 I believe, and in cp437 those Cyrillic chars from cp866 look like you put it above. Note that if you clone the repository using git to your local machine, you will get question marks instead of pseudographics because the UTF-8 -> cp437 converter will detect that it can't represent Cyrillics in this codepage and substitute them with ???.

I will try to deal with that in the next import (within #1) by forcing LANG=en_US (I could also disable keyword substitution when exporting from SVN but at least $Revision is used in the kbuild sources in version strings so it's probably not a good idea).

Anyway, not actually a bug of kBuild (it won't even affect visual appearance of this HTML file given that this is a comment block), so closing this.
